[tool.poetry]
name = "language-to-policies"
version = "0.1.0"
description = ""
authors = ["K.R. Zentner <krzentner@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
openai = "^0.18.1"
python-dotenv = "^0.20.0"
setuptools = "^62.3.1"
pip = "^22.1"
metaworld = {path = "metaworld", develop = true}
jupyterlab = "^3.4.3"
scipy = "^1.8.1"
PyQt5 = "^5.15.7"
open3d = "^0.15.2"
Pillow = "^9.1.1"
ipdb = "^0.13.9"
dash = "^2.5.1"
plotly = "^5.8.2"
pandas = "^1.4.2"
torch = "^1.11.0"
pytest = "^7.1.2"
ftfy = "^6.1.1"
regex = "^2022.6.2"
tqdm = "^4.64.0"
fvcore = "^0.1.5"
imageio = "^2.19.3"
imageio-ffmpeg = "^0.4.7"
pybullet = "^3.2.5"
moviepy = "^1.0.3"
flax = "^0.5.2"
easydict = "^1.9"
clip = {git = "https://github.com/openai/CLIP.git", rev = "b46f5ac7587d2e1862f8b7b1573179d80dcdd620"}
gdown = "^4.4.0"
opencv-python = "^4.6.0"
torchvision = "^0.12.0"
tensorflow = "^2.9.1"

[tool.poetry.dev-dependencies]
ipython = "^8.3.0"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "setuptools.build_meta"
