[tool.poetry]
name = "language-to-policies"
version = "0.1.0"
description = ""
authors = ["K.R. Zentner <krzentner@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
openai = "^0.18.1"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
ipython = "^8.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
