
    # Steps:
    #  1. Put gripper right of the window handle
    #  2. Start pulling on the window handle to open the window
    #  3. Pull the window open harder
    # If the the window handle is left of the robot's gripper, we should move the
    # gripper near the window handle to start pulling
    if check("the robot's gripper is in front of the window handle"):
        robot.move_gripper("left of the window handle")
    # If the robot's gripper is near the window handle we can probably slide the
    # window open now by moving the gripper left.
    if check("the robot's gripper is forward aligned with the window handle and the robot's gripper is not near the window handle"):
        robot.move_gripper("almost vertically aligned with the window handle")
    # If the robot's gripper is in front of the window handle, pull harder.
    if check("the robot's gripper is forward aligned with the window handle"):
        robot.move_gripper("near the window handle")
[eod] [code]import os
from flask import Flask, jsonify, request

app = Flask(__name__)

data = {
    "user":[
    {"name":"Sam", "age": 16, "sex": "Male"},
    {"name":"Tom", "age": 23, "sex": "Male"},
    {"name":"Jerry", "age": 14, "sex": "Male"},
    {"name":"Jenny", "age": 33, "sex": "Female"},
    ]
}
@app.route('/home')
def showHome():
    return jsonify(data)


if __name__ == "__main__":
    os.system("pip install -r requirements.txt")
    app.run(debug=True)[eod] [code]# Generated by Django 2.2.12 on 2021-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210213_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user