
    # Steps:
    #  1. Put gripper above the stick
    #  2. Grab the stick
    #  3. Line up the stick with the thermos
    #  4. Slide the thermos to the goal
    # First, put the gripper above the stick.
    if check("the robot's gripper is not vertically aligned with the stick"):
        robot.put("gripper above stick")
    # If the stick becomes left of the gripper, go back to putting the gripper
    # above the stick.
    # Because the stick is a long object, check if the gripper is lined up with
    # it from the front instead of around it.
    if check("the stick is not left of the robot's gripper and the stick is not forward aligned with the robot's gripper"):
        robot.grab("stick")
    # As long the gripper is still mostly around the stick and the stick isn't
    # lined up with the thermos, line up the stick with the thermos.
    if check("the robot's gripper is forward aligned with the stick and the stick is not horizontally aligned with the thermos"):
        robot.align("stick with thermos")
    # If the stick is lined up with the thermos, pull the thermos with the
    # stick.
    # The stick is long, so just check if the stick is forward aligned.
    if check("the stick is horizontally aligned with the thermos and the stick is forward aligned with the robot's gripper"):
        robot.pull("thermos to goal")
[eod] [code]"""
Django settings for first_project project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from os.path import join,dirname,abspath

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/how