
    # Steps:
    #  1. Put gripper right of the window handle
    #  2. Start pulling on the window handle to open the window
    #  3. Pull the window open harder
    # If the the window handle is left of the robot's gripper, we should move the
    # gripper near the window handle to start pushing
    if check("the window handle is left of the robot's gripper and the robot's gripper is not near the window handle"):
        robot.move("gripper to right of window handle")
    # If the robot's gripper is near the window handle we can probably slide the
    # window open now by moving the gripper left.
    if check("the robot's gripper is near the window handle"):
        robot.slide("window left")
    # If the robot's gripper is starting to be behind of the window handle,
    # pull harder.
    if check("the robot's gripper is behind the window handle"):
        robot.pull("window left harder")
[eod] [code]from .. import Provider as AutomotiveProvider


class Provider(AutomotiveProvider):
    # source:
    # https://www.autoscout24.nl/lijst-van-alle-merken/3-b
    license_formats = (
        "??-??-???",
        "??-???-?",
        "???-??-?",
        "??-??-??",
    )
[eod] [code]# Generated by Django 3.0.3 on 2020-04-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto