from dataclasses import dataclass
from metaworld.policies import *

POLICY_MAP = {
    'assembly-v1': SawyerAssemblyV1Policy(),
    'assembly-v2': SawyerAssemblyV2Policy(),
    'basketball-v1': SawyerBasketballV1Policy(),
    'basketball-v2': SawyerBasketballV2Policy(),
    'bin-picking-v2': SawyerBinPickingV2Policy(),
    'box-close-v1': SawyerBoxCloseV1Policy(),
    'box-close-v2': SawyerBoxCloseV2Policy(),
    'button-press-topdown-v1': SawyerButtonPressTopdownV1Policy(),
    'button-press-topdown-v2': SawyerButtonPressTopdownV2Policy(),
    'button-press-topdown-wall-v1': SawyerButtonPressTopdownWallV1Policy(),
    'button-press-topdown-wall-v2': SawyerButtonPressTopdownWallV2Policy(),
    'button-press-v1': SawyerButtonPressV1Policy(),
    'button-press-v2': SawyerButtonPressV2Policy(),
    'button-press-wall-v1': SawyerButtonPressWallV1Policy(),
    'button-press-wall-v2': SawyerButtonPressWallV2Policy(),
    'coffee-button-v1': SawyerCoffeeButtonV1Policy(),
    'coffee-button-v2': SawyerCoffeeButtonV2Policy(),
    'coffee-pull-v1': SawyerCoffeePullV1Policy(),
    'coffee-pull-v2': SawyerCoffeePullV2Policy(),
    'coffee-push-v1': SawyerCoffeePushV1Policy(),
    'coffee-push-v2': SawyerCoffeePushV2Policy(),
    'dial-turn-v1': SawyerDialTurnV1Policy(),
    'dial-turn-v2': SawyerDialTurnV2Policy(),
    'disassemble-v1': SawyerDisassembleV1Policy(),
    'disassemble-v2': SawyerDisassembleV2Policy(),
    'door-close-v1': SawyerDoorCloseV1Policy(),
    'door-close-v2': SawyerDoorCloseV2Policy(),
    'door-lock-v1': SawyerDoorLockV1Policy(),
    'door-lock-v2': SawyerDoorLockV2Policy(),
    'door-open-v1': SawyerDoorOpenV1Policy(),
    'door-open-v2': SawyerDoorOpenV2Policy(),
    'door-unlock-v1': SawyerDoorUnlockV1Policy(),
    'door-unlock-v2': SawyerDoorUnlockV2Policy(),
    'drawer-close-v1': SawyerDrawerCloseV1Policy(),
    'drawer-close-v2': SawyerDrawerCloseV2Policy(),
    'drawer-open-v1': SawyerDrawerOpenV1Policy(),
    'drawer-open-v2': SawyerDrawerOpenV2Policy(),
    'faucet-close-v1': SawyerFaucetCloseV1Policy(),
    'faucet-close-v2': SawyerFaucetCloseV2Policy(),
    'faucet-open-v1': SawyerFaucetOpenV1Policy(),
    'faucet-open-v2': SawyerFaucetOpenV2Policy(),
    'hammer-v1': SawyerHammerV1Policy(),
    'hammer-v2': SawyerHammerV2Policy(),
    'hand-insert-v1': SawyerHandInsertV1Policy(),
    'hand-insert-v2': SawyerHandInsertV2Policy(),
    'handle-press-side-v2': SawyerHandlePressSideV2Policy(),
    'handle-press-v1': SawyerHandlePressV1Policy(),
    'handle-press-v2': SawyerHandlePressV2Policy(),
    'handle-pull-v1': SawyerHandlePullV1Policy(),
    'handle-pull-v2': SawyerHandlePullV2Policy(),
    'handle-pull-side-v1': SawyerHandlePullSideV1Policy(),
    'handle-pull-side-v2': SawyerHandlePullSideV2Policy(),
    'peg-insert-side-v2': SawyerPegInsertionSideV2Policy(),
    'lever-pull-v2': SawyerLeverPullV2Policy(),
    'peg-unplug-side-v1': SawyerPegUnplugSideV1Policy(),
    'peg-unplug-side-v2': SawyerPegUnplugSideV2Policy(),
    'pick-out-of-hole-v1': SawyerPickOutOfHoleV1Policy(),
    'pick-out-of-hole-v2': SawyerPickOutOfHoleV2Policy(),
    'pick-place-v2': SawyerPickPlaceV2Policy(),
    'pick-place-wall-v2': SawyerPickPlaceWallV2Policy(),
    'plate-slide-back-side-v2': SawyerPlateSlideBackSideV2Policy(),
    'plate-slide-back-v1': SawyerPlateSlideBackV1Policy(),
    'plate-slide-back-v2': SawyerPlateSlideBackV2Policy(),
    'plate-slide-side-v1': SawyerPlateSlideSideV1Policy(),
    'plate-slide-side-v2': SawyerPlateSlideSideV2Policy(),
    'plate-slide-v1': SawyerPlateSlideV1Policy(),
    'plate-slide-v2': SawyerPlateSlideV2Policy(),
    'reach-v2': SawyerReachV2Policy(),
    'reach-wall-v2': SawyerReachWallV2Policy(),
    'push-back-v1': SawyerPushBackV1Policy(),
    'push-back-v2': SawyerPushBackV2Policy(),
    'push-v2': SawyerPushV2Policy(),
    'push-wall-v2': SawyerPushWallV2Policy(),
    'shelf-place-v1': SawyerShelfPlaceV1Policy(),
    'shelf-place-v2': SawyerShelfPlaceV2Policy(),
    'soccer-v1': SawyerSoccerV1Policy(),
    'soccer-v2': SawyerSoccerV2Policy(),
    'stick-pull-v1': SawyerStickPullV1Policy(),
    'stick-pull-v2': SawyerStickPullV2Policy(),
    'stick-push-v1': SawyerStickPushV1Policy(),
    'stick-push-v2': SawyerStickPushV2Policy(),
    'sweep-into-v1': SawyerSweepIntoV1Policy(),
    'sweep-into-v2':  SawyerSweepIntoV2Policy(),
    'sweep-v1': SawyerSweepV1Policy(),
    'sweep-v2': SawyerSweepV2Policy(),
    'window-close-v2': SawyerWindowCloseV2Policy(),
    'window-open-v2': SawyerWindowOpenV2Policy(),
}


@dataclass
class SawyerUniversalV2Policy:

    env_name: str or None = None

    def get_action(self, observation):
      policy = POLICY_MAP[self.env_name + '-v2']
      action = policy.get_action(observation)
      return action, {'env_name': self.env_name}
