import tensorflow_hub as hub
import numpy as np

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-large/5")
# embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
embeddings = embed(
    [
        "Is is true that the robot's gripper is above the drawer?",
        "Is is true that the robot's gripper is below the drawer?",
        "the robot's gripper is above the drawer",
        "the robot's gripper is below the drawer",
    ]
)

print(np.dot(embeddings[0], embeddings[1]))
print(np.dot(embeddings[2], embeddings[3]))

descriptor_counts = {
    "button is around the robot's gripper": 18801,
    "button is behind the robot's gripper": 2423,
    "button is below the robot's gripper": 2020,
    "button is in front of the robot's gripper": 2256,
    "button is left of the robot's gripper": 7163,
    "button is near the robot's gripper": 18801,
    "button is not above the robot's gripper": 50100,
    "button is not around the robot's gripper": 31299,
    "button is not behind the robot's gripper": 47677,
    "button is not below the robot's gripper": 48080,
    "button is not in front of the robot's gripper": 47844,
    "button is not left of the robot's gripper": 42937,
    "button is not near the robot's gripper": 31299,
    "button is not right of the robot's gripper": 44611,
    "button is right of the robot's gripper": 5489,
    "door handle is around the robot's gripper": 2301,
    "door handle is behind the robot's gripper": 83,
    "door handle is below the robot's gripper": 289,
    "door handle is in front of the robot's gripper": 2981,
    "door handle is left of the robot's gripper": 19324,
    "door handle is near the robot's gripper": 2301,
    "door handle is not above the robot's gripper": 50100,
    "door handle is not around the robot's gripper": 47799,
    "door handle is not behind the robot's gripper": 50017,
    "door handle is not below the robot's gripper": 49811,
    "door handle is not in front of the robot's gripper": 47119,
    "door handle is not left of the robot's gripper": 30776,
    "door handle is not near the robot's gripper": 47799,
    "door handle is not right of the robot's gripper": 32990,
    "door handle is right of the robot's gripper": 17110,
    "drawer handle is above the robot's gripper": 744,
    "drawer handle is around the robot's gripper": 24111,
    "drawer handle is behind the robot's gripper": 2079,
    "drawer handle is below the robot's gripper": 2882,
    "drawer handle is in front of the robot's gripper": 1295,
    "drawer handle is left of the robot's gripper": 16342,
    "drawer handle is near the robot's gripper": 24111,
    "drawer handle is not above the robot's gripper": 99456,
    "drawer handle is not around the robot's gripper": 76089,
    "drawer handle is not behind the robot's gripper": 98121,
    "drawer handle is not below the robot's gripper": 97318,
    "drawer handle is not in front of the robot's gripper": 98905,
    "drawer handle is not left of the robot's gripper": 83858,
    "drawer handle is not near the robot's gripper": 76089,
    "drawer handle is not right of the robot's gripper": 86467,
    "drawer handle is right of the robot's gripper": 13733,
    "hole is below the robot's gripper": 56,
    "hole is left of peg": 50100,
    "hole is left of the robot's gripper": 49560,
    "hole is not above peg": 50100,
    "hole is not above the robot's gripper": 50100,
    "hole is not around peg": 50100,
    "hole is not around the robot's gripper": 50100,
    "hole is not behind peg": 50100,
    "hole is not behind the robot's gripper": 50100,
    "hole is not below peg": 50100,
    "hole is not below the robot's gripper": 50044,
    "hole is not in front of peg": 50100,
    "hole is not in front of the robot's gripper": 50100,
    "hole is not left of the robot's gripper": 540,
    "hole is not near peg": 50100,
    "hole is not near the robot's gripper": 50100,
    "hole is not right of peg": 50100,
    "hole is not right of the robot's gripper": 49723,
    "hole is right of the robot's gripper": 377,
    "peg is above the robot's gripper": 48,
    "peg is around the robot's gripper": 19389,
    "peg is behind the robot's gripper": 168,
    "peg is below the robot's gripper": 5340,
    "peg is in front of the robot's gripper": 129,
    "peg is left of the robot's gripper": 9174,
    "peg is near the robot's gripper": 19389,
    "peg is not above hole": 50100,
    "peg is not above the robot's gripper": 50052,
    "peg is not around hole": 50100,
    "peg is not around the robot's gripper": 30711,
    "peg is not behind hole": 50100,
    "peg is not behind the robot's gripper": 49932,
    "peg is not below hole": 50100,
    "peg is not below the robot's gripper": 44760,
    "peg is not in front of hole": 50100,
    "peg is not in front of the robot's gripper": 49971,
    "peg is not left of hole": 50100,
    "peg is not left of the robot's gripper": 40926,
    "peg is not near hole": 50100,
    "peg is not near the robot's gripper": 30711,
    "peg is not right of the robot's gripper": 44070,
    "peg is right of hole": 50100,
    "peg is right of the robot's gripper": 6030,
    "puck is around target location": 23758,
    "puck is around the robot's gripper": 22260,
    "puck is behind target location": 3746,
    "puck is behind the robot's gripper": 669,
    "puck is below target location": 6570,
    "puck is below the robot's gripper": 13681,
    "puck is in front of target location": 3893,
    "puck is in front of the robot's gripper": 119,
    "puck is left of target location": 37714,
    "puck is left of the robot's gripper": 23095,
    "puck is near target location": 23758,
    "puck is near the robot's gripper": 22260,
    "puck is not above target location": 100200,
    "puck is not above the robot's gripper": 100200,
    "puck is not around target location": 76442,
    "puck is not around the robot's gripper": 77940,
    "puck is not behind target location": 96454,
    "puck is not behind the robot's gripper": 99531,
    "puck is not below target location": 93630,
    "puck is not below the robot's gripper": 86519,
    "puck is not in front of target location": 96307,
    "puck is not in front of the robot's gripper": 100081,
    "puck is not left of target location": 62486,
    "puck is not left of the robot's gripper": 77105,
    "puck is not near target location": 76442,
    "puck is not near the robot's gripper": 77940,
    "puck is not right of target location": 96274,
    "puck is not right of the robot's gripper": 87533,
    "puck is right of target location": 3926,
    "puck is right of the robot's gripper": 12667,
    "reach target is around the robot's gripper": 13506,
    "reach target is behind the robot's gripper": 3371,
    "reach target is below the robot's gripper": 580,
    "reach target is in front of the robot's gripper": 882,
    "reach target is left of the robot's gripper": 11224,
    "reach target is near the robot's gripper": 13506,
    "reach target is not above the robot's gripper": 50100,
    "reach target is not around the robot's gripper": 36594,
    "reach target is not behind the robot's gripper": 46729,
    "reach target is not below the robot's gripper": 49520,
    "reach target is not in front of the robot's gripper": 49218,
    "reach target is not left of the robot's gripper": 38876,
    "reach target is not near the robot's gripper": 36594,
    "reach target is not right of the robot's gripper": 39007,
    "reach target is right of the robot's gripper": 11093,
    "target location is above puck": 6570,
    "target location is around puck": 23758,
    "target location is around the robot's gripper": 15714,
    "target location is behind puck": 3893,
    "target location is behind the robot's gripper": 5463,
    "target location is below the robot's gripper": 2432,
    "target location is in front of puck": 3746,
    "target location is in front of the robot's gripper": 2393,
    "target location is left of puck": 3926,
    "target location is left of the robot's gripper": 20137,
    "target location is near puck": 23758,
    "target location is near the robot's gripper": 15714,
    "target location is not above puck": 93630,
    "target location is not above the robot's gripper": 100200,
    "target location is not around puck": 76442,
    "target location is not around the robot's gripper": 84486,
    "target location is not behind puck": 96307,
    "target location is not behind the robot's gripper": 94737,
    "target location is not below puck": 100200,
    "target location is not below the robot's gripper": 97768,
    "target location is not in front of puck": 96454,
    "target location is not in front of the robot's gripper": 97807,
    "target location is not left of puck": 96274,
    "target location is not left of the robot's gripper": 80063,
    "target location is not near puck": 76442,
    "target location is not near the robot's gripper": 84486,
    "target location is not right of puck": 62486,
    "target location is not right of the robot's gripper": 65451,
    "target location is right of puck": 37714,
    "target location is right of the robot's gripper": 34749,
    "the robot's gripper is above button": 2020,
    "the robot's gripper is above door handle": 289,
    "the robot's gripper is above drawer handle": 2882,
    "the robot's gripper is above hole": 56,
    "the robot's gripper is above peg": 5340,
    "the robot's gripper is above puck": 13681,
    "the robot's gripper is above reach target": 580,
    "the robot's gripper is above target location": 2432,
    "the robot's gripper is above window handle": 169,
    "the robot's gripper is around button": 18801,
    "the robot's gripper is around door handle": 2301,
    "the robot's gripper is around drawer handle": 24111,
    "the robot's gripper is around peg": 19389,
    "the robot's gripper is around puck": 22260,
    "the robot's gripper is around reach target": 13506,
    "the robot's gripper is around target location": 15714,
    "the robot's gripper is around window handle": 411,
    "the robot's gripper is behind button": 2256,
    "the robot's gripper is behind door handle": 2981,
    "the robot's gripper is behind drawer handle": 1295,
    "the robot's gripper is behind peg": 129,
    "the robot's gripper is behind puck": 119,
    "the robot's gripper is behind reach target": 882,
    "the robot's gripper is behind target location": 2393,
    "the robot's gripper is below drawer handle": 744,
    "the robot's gripper is below peg": 48,
    "the robot's gripper is below window handle": 1544,
    "the robot's gripper is in front of button": 2423,
    "the robot's gripper is in front of door handle": 83,
    "the robot's gripper is in front of drawer handle": 2079,
    "the robot's gripper is in front of peg": 168,
    "the robot's gripper is in front of puck": 669,
    "the robot's gripper is in front of reach target": 3371,
    "the robot's gripper is in front of target location": 5463,
    "the robot's gripper is in front of window handle": 761,
    "the robot's gripper is left of button": 5489,
    "the robot's gripper is left of door handle": 17110,
    "the robot's gripper is left of drawer handle": 13733,
    "the robot's gripper is left of hole": 377,
    "the robot's gripper is left of peg": 6030,
    "the robot's gripper is left of puck": 12667,
    "the robot's gripper is left of reach target": 11093,
    "the robot's gripper is left of target location": 34749,
    "the robot's gripper is left of window handle": 29211,
    "the robot's gripper is near button": 18801,
    "the robot's gripper is near door handle": 2301,
    "the robot's gripper is near drawer handle": 24111,
    "the robot's gripper is near peg": 19389,
    "the robot's gripper is near puck": 22260,
    "the robot's gripper is near reach target": 13506,
    "the robot's gripper is near target location": 15714,
    "the robot's gripper is near window handle": 411,
    "the robot's gripper is not above button": 48080,
    "the robot's gripper is not above door handle": 49811,
    "the robot's gripper is not above drawer handle": 97318,
    "the robot's gripper is not above hole": 50044,
    "the robot's gripper is not above peg": 44760,
    "the robot's gripper is not above puck": 86519,
    "the robot's gripper is not above reach target": 49520,
    "the robot's gripper is not above target location": 97768,
    "the robot's gripper is not above window handle": 100031,
    "the robot's gripper is not around button": 31299,
    "the robot's gripper is not around door handle": 47799,
    "the robot's gripper is not around drawer handle": 76089,
    "the robot's gripper is not around hole": 50100,
    "the robot's gripper is not around peg": 30711,
    "the robot's gripper is not around puck": 77940,
    "the robot's gripper is not around reach target": 36594,
    "the robot's gripper is not around target location": 84486,
    "the robot's gripper is not around window handle": 99789,
    "the robot's gripper is not behind button": 47844,
    "the robot's gripper is not behind door handle": 47119,
    "the robot's gripper is not behind drawer handle": 98905,
    "the robot's gripper is not behind hole": 50100,
    "the robot's gripper is not behind peg": 49971,
    "the robot's gripper is not behind puck": 100081,
    "the robot's gripper is not behind reach target": 49218,
    "the robot's gripper is not behind target location": 97807,
    "the robot's gripper is not behind window handle": 100200,
    "the robot's gripper is not below button": 50100,
    "the robot's gripper is not below door handle": 50100,
    "the robot's gripper is not below drawer handle": 99456,
    "the robot's gripper is not below hole": 50100,
    "the robot's gripper is not below peg": 50052,
    "the robot's gripper is not below puck": 100200,
    "the robot's gripper is not below reach target": 50100,
    "the robot's gripper is not below target location": 100200,
    "the robot's gripper is not below window handle": 98656,
    "the robot's gripper is not in front of button": 47677,
    "the robot's gripper is not in front of door handle": 50017,
    "the robot's gripper is not in front of drawer handle": 98121,
    "the robot's gripper is not in front of hole": 50100,
    "the robot's gripper is not in front of peg": 49932,
    "the robot's gripper is not in front of puck": 99531,
    "the robot's gripper is not in front of reach target": 46729,
    "the robot's gripper is not in front of target location": 94737,
    "the robot's gripper is not in front of window handle": 99439,
    "the robot's gripper is not left of button": 44611,
    "the robot's gripper is not left of door handle": 32990,
    "the robot's gripper is not left of drawer handle": 86467,
    "the robot's gripper is not left of hole": 49723,
    "the robot's gripper is not left of peg": 44070,
    "the robot's gripper is not left of puck": 87533,
    "the robot's gripper is not left of reach target": 39007,
    "the robot's gripper is not left of target location": 65451,
    "the robot's gripper is not left of window handle": 70989,
    "the robot's gripper is not near button": 31299,
    "the robot's gripper is not near door handle": 47799,
    "the robot's gripper is not near drawer handle": 76089,
    "the robot's gripper is not near hole": 50100,
    "the robot's gripper is not near peg": 30711,
    "the robot's gripper is not near puck": 77940,
    "the robot's gripper is not near reach target": 36594,
    "the robot's gripper is not near target location": 84486,
    "the robot's gripper is not near window handle": 99789,
    "the robot's gripper is not right of button": 42937,
    "the robot's gripper is not right of door handle": 30776,
    "the robot's gripper is not right of drawer handle": 83858,
    "the robot's gripper is not right of hole": 540,
    "the robot's gripper is not right of peg": 40926,
    "the robot's gripper is not right of puck": 77105,
    "the robot's gripper is not right of reach target": 38876,
    "the robot's gripper is not right of target location": 80063,
    "the robot's gripper is not right of window handle": 65166,
    "the robot's gripper is right of button": 7163,
    "the robot's gripper is right of door handle": 19324,
    "the robot's gripper is right of drawer handle": 16342,
    "the robot's gripper is right of hole": 49560,
    "the robot's gripper is right of peg": 9174,
    "the robot's gripper is right of puck": 23095,
    "the robot's gripper is right of reach target": 11224,
    "the robot's gripper is right of target location": 20137,
    "the robot's gripper is right of window handle": 35034,
    "window handle is above the robot's gripper": 1544,
    "window handle is around the robot's gripper": 411,
    "window handle is behind the robot's gripper": 761,
    "window handle is below the robot's gripper": 169,
    "window handle is left of the robot's gripper": 35034,
    "window handle is near the robot's gripper": 411,
    "window handle is not above the robot's gripper": 98656,
    "window handle is not around the robot's gripper": 99789,
    "window handle is not behind the robot's gripper": 99439,
    "window handle is not below the robot's gripper": 100031,
    "window handle is not in front of the robot's gripper": 100200,
    "window handle is not left of the robot's gripper": 65166,
    "window handle is not near the robot's gripper": 99789,
    "window handle is not right of the robot's gripper": 70989,
    "window handle is right of the robot's gripper": 29211,
}
